### ISSUE TITLE
Free variables warning: ido-cr+-debug-mode ido-require-match ido-cur-list

### ISSUE THREAD

**Issue by zahardzhan** [DarwinAwardWinner/ido-ubiquitous#100]
Running Emacs 25 -q session:

    (require 'cl-lib)
    (require 'package)
    (package-initialize)
    (cl-pushnew (cons "melpa" "http://melpa.milkbox.net/packages/") package-archives :test #'equal)
    (package-refresh-contents)
    (package-install 'ido-ubiquitous)

Compile Log:

    Compiling file c:/Users/haru/.emacs.d/elpa/ido-ubiquitous-20151121.1415/ido-ubiquitous.el
    Entering directory ‘c:/Users/haru/.emacs.d/elpa/ido-ubiquitous-20151121.1415/’
    ido-ubiquitous.el:88:2:Warning: reference to free variable ‘ido-require-match’
    ido-ubiquitous.el:88:2:Warning: reference to free variable ‘ido-cur-list’
    ido-ubiquitous.el:88:2:Warning: reference to free variable
        ‘ido-cr+-debug-mode’

Then

    (require 'ido-ubiquitous)

Compile Log:

    Compiling no file at Wed Nov 25 17:13:37 2015
    ido-ubiquitous.elc:Warning: reference to free variable ‘ido-require-match’
    ido-ubiquitous.elc:Warning: reference to free variable ‘ido-cur-list’
    ido-ubiquitous.elc:Warning: reference to free variable ‘ido-require-match’
    ido-ubiquitous.elc:Warning: reference to free variable ‘ido-cur-list’

Exit Emacs.

Then run Emacs 25 -q again and:

    (require 'package)
    (package-initialize)
    (require 'ido-ubiquitous)

Compile Log:

    .emacs.d/elpa/ido-completing-read+-20151124.853/ido-completing-read+.elc:Warning:
        reference to free variable ‘ido-require-match’
    .emacs.d/elpa/ido-completing-read+-20151124.853/ido-completing-read+.elc:Warning:
        reference to free variable ‘ido-cur-list’
    .emacs.d/elpa/ido-completing-read+-20151124.853/ido-completing-read+.elc:Warning:
        reference to free variable ‘ido-cr+-debug-mode’
    .emacs.d/elpa/ido-ubiquitous-20151121.1415/ido-ubiquitous.elc:Warning:
        reference to free variable ‘ido-require-match’
    .emacs.d/elpa/ido-ubiquitous-20151121.1415/ido-ubiquitous.elc:Warning:
        reference to free variable ‘ido-cur-list’
    .emacs.d/elpa/ido-ubiquitous-20151121.1415/ido-ubiquitous.elc:Warning:
        reference to free variable ‘ido-require-match’
    .emacs.d/elpa/ido-ubiquitous-20151121.1415/ido-ubiquitous.elc:Warning:
        reference to free variable ‘ido-cur-list’

After applying patch d4cb80a that checks free vars ido-cr+-debug-mode ido-cur-list and ido-require-match in code with bound-and-true-p then run Emacs 25 -q:

    (require 'package)
    (package-initialize)
    (require 'bytecomp)
    (delete-file "~/.emacs.d/elpa/ido-completing-read+-20151124.853/ido-completing-read+.elc")
    (byte-compile-file "~/.emacs.d/elpa/ido-completing-read+-20151124.853/ido-completing-read+.el")
    (require 'ido-ubiquitous)

Compile Log:

    Compiling file c:/Users/haru/.emacs.d/elpa/ido-completing-read+-20151124.853/ido-completing-read+.el at Wed Nov 25 17:24:54 2015
    Compiling no file at Wed Nov 25 17:28:22 2015

And NO WARNINGS.

Emacs 25.0.50.1 64bit Windows 10.

**Comment by DarwinAwardWinner** [comment]
Thanks for the instructions. When I get the chance, I'll see if I can get my Emacs to actually produce these warnings so I can verify that the patch fixes them.

**Comment by DarwinAwardWinner** [comment]
I've just pushed what is hopefully a fix. It should land in MELPA soon. If `ido-ubiquitous-version` is 3.9, you have the fix. Please let me know if it eliminates these warnings.

**Comment by zahardzhan** [comment]
Your fix eliminates these warnings (in brute-force way :), so now its OK.

But commit 542dade introduce some new warnings:

    Compiling file .emacs.d/elpa/ido-ubiquitous-20151129.1526/ido-ubiquitous.el
    Warning (bytecomp): Unused lexical variable ‘final-value’
    Warning (bytecomp): Unused lexical variable ‘overridden-functions’

Because of this:

    (macroexpand-all '(cl-loop with final-value = nil <= DONT DO THIS
                               for override = 'something
                               collect override into final-value
                               finally return final-value))

    (let* ((final-value nil) <= BECAUSE OF 'with final-value = nil'
           (override nil)
           (final-value nil)) <= BECAUSE OF 'collect into final-value'
      (while t (setq override (quote something))
             (setq final-value (nconc final-value ...)))
      final-value)

There must not be 'with overridden-functions = nil' and 'with final-value = nil' in body of loop macro.

**Comment by DarwinAwardWinner** [comment]
Ah, I see the problem. I forgot that collect already declares the collection variable, so I don't have to initialize those variables.
