### ISSUE TITLE
auto-updating of overrides should not add variables to custom.el unless they were already in there

### ISSUE THREAD

**Issue by DarwinAwardWinner** [DarwinAwardWinner/ido-ubiquitous#104]

**Comment by DarwinAwardWinner** [comment]
@dgutov The code that decides whether or not to save the variable to custom.el is here: https://github.com/DarwinAwardWinner/ido-ubiquitous/blob/master/ido-ubiquitous.el#L852-L907. It uses `custom-variable-state` to figure our whether each var has been customized by the user. However, the only state that it considers as "un-customized" is "standard". Thinking about it, I don't really have a good understanding of what all the states mean, so I'm guessing my logic is oversimplified in this function.

**Comment by dgutov** [comment]
It's not like I understand the Customize machinery very well. I just get

```
Updated the following ido-ubiquitous override variables: (ido-ubiquitous-command-overrides)
```

whenever I upgrade (or reinstall) this package. No matter if I have the value in `.custom` or not.

**Comment by DarwinAwardWinner** [comment]
Can you please tell me what `(custom-variable-state 'ido-ubiquitous-command-overrides nil)` returns? Also, can you paste the full value of `ido-ubiquitous-command-overrides` and the version of ido-ubiquitous you're using?

**Comment by dgutov** [comment]
I have this in my init script:

```el
(eval-after-load 'ido-ubiquitous
  '(delete '(enable prefix "xref-") ido-ubiquitous-command-overrides))
```

**Comment by dgutov** [comment]
> Can you please tell me what (custom-variable-state 'ido-ubiquitous-command-overrides nil) returns?

changed

**Comment by DarwinAwardWinner** [comment]
Ah, ok, so you're modifying it outside of M-x customize. I'm in the process of figuring out what values that function can return and what each one of them means so I can fix the logic in my update code.

**Comment by dgutov** [comment]
Thanks.
