### ISSUE TITLE
Remove overrides for org mode

### ISSUE THREAD

**Issue by vspinu** [DarwinAwardWinner/ido-ubiquitous#107]
New org mode has depricated `org-completion-use-ido`. It's plain completion read right now. So it's safe to remove the override.

**Comment by DarwinAwardWinner** [comment]
Ok. I assume the feature was deprecated in favor of just letting users customize `completing-read-function`, rather than being deprecated due to some discovered incompatibility between ido and org?

**Comment by DarwinAwardWinner** [comment]
Note: Also update the documentation about how to enable ido everywhere, since that mentions org-mode specifically.
