### ISSUE TITLE
ido-completing-read+ : what to do with it?

### ISSUE THREAD

**Issue by Trevoke** [DarwinAwardWinner/ido-ubiquitous#109]
I'm not sure what to do with the documentation at the bottom. Do I need to install that and use it separately? Will it get pulled as a requirement by `ido-ubiquitous` ?

**Comment by DarwinAwardWinner** [comment]
Yes, it will get pulled in as a dependency. From the very end of the readme: 

> As a user, you don't really need to know anything about ido-cr+. However, if you are writing an Emacs package and would like to incorporate ido completion, you may wish to use ido-cr+ to get more robust completion with fewer weird edge cases.

**Comment by Trevoke** [comment]
Thank you. I didn't understand the implications.
