### ISSUE TITLE
ido-ubiquitous v3.0+ causes double-insert of content in dired in Emacs 25.1

### ISSUE THREAD

**Issue by mwolson** [DarwinAwardWinner/ido-ubiquitous#113]
Steps:

* Install Emacs 25.1
* Use ido-ubiquitous v3.0 or higher
* Visit a folder in dired
* Hit `g` to refresh the buffer
* Notice that the buffer contents are repeated

When I downgraded all the way down to v2.17, the problem went away, but was left with some compilation warnings about free variables.

**Comment by DarwinAwardWinner** [comment]
Thanks for reporting this. I'll look into it when I have a chance. 

However, note that ido-ubiquitous v2.x will likely have other issues running on Emacs 25, since it is quite an old version.

**Comment by DarwinAwardWinner** [comment]
I'm not seeing this issue on my machine. With Emacs 25.1.1, I ran:

    emacs -Q -l ido-completing-read+.el -l ido-ubiquitous.el -f ido-ubiquitous-mode ~/

And then pressed g repeatedly, and the buffer contents were not repeated. I'm on MacOS 10.11.6, using this version of Emacs: https://emacsformacosx.com/

**Comment by mwolson** [comment]
I figured out what it was -- I had some defadvice in my .emacs file around erase-buffer that was getting activated by default (apparently a new behavior of Emacs 25) so it was making erase-buffer do nothing. Going to close this one out.
