### ISSUE TITLE
ido for visit-tags-table

### ISSUE THREAD

**Issue by joelmo** [DarwinAwardWinner/ido-ubiquitous#114]
I would like to use ido for visit-tags-table (https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/etags.el#L286).

**Comment by DarwinAwardWinner** [comment]
It looks like `visit-tags-table` reads a file name, which is out of scope for ido-ubiquitous. You should be able to get ido completion here just by enabling `ido-everywhere`.

**Comment by joelmo** [comment]
Thanks! I get ido completions now.
