### ISSUE TITLE
My emacs setup is getting these warnings related to ido-ubiquitous package. Could you help?

### ISSUE THREAD

**Issue by pradeepcheers** [DarwinAwardWinner/ido-ubiquitous#115]
Every time I open emacs, I get the following warning. Could you help me to fix it please?

``Warning (bytecomp): reference to free variable ‘ido-default-item’ [3 times]``

**Comment by DarwinAwardWinner** [comment]
See the FAQ: https://github.com/DarwinAwardWinner/ido-ubiquitous#im-getting-some-weird-warnings-from-ido-ubiquitous-when-emacs-starts

**Comment by pradeepcheers** [comment]
Sorry, fixed it by enabling Ido-everywhere. Thanks

``M-x ido-everywhere``
