### ISSUE TITLE
Needs overrides for project.el

### ISSUE THREAD

**Issue by mattheww** [DarwinAwardWinner/ido-ubiquitous#116]
I found I needed overrides to enable ido-ubiquitous for project-find-file and project-or-external-find-file from progmodes/project.el (as shipped with emacs 25.1):

     (enable exact "project-find-file")
     (enable exact "project-or-external-find-file")

debug-mode said

> Falling back to ‘completing-read-default’ because ido-ubiquitous encountered an unexpected error: (ido-ubiquitous-fallback . "COLLECTION is a function and there is no override").

**Comment by DarwinAwardWinner** [comment]
Can you give a link to the "project" package? I can find several similar-sounding packages, but none that have function called `project-find-file`.

**Comment by mattheww** [comment]
It's shipped with emacs itself. This one:
http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/project.el?h=emacs-25
