### ISSUE TITLE
ido-ubiquitious has stopped working with bookmarks (again)

### ISSUE THREAD

**Issue by ylluminarious** [DarwinAwardWinner/ido-ubiquitous#120]
I see that this bug has happened before with #36, so maybe it's the same problem all over again. Anyway, I recently updated `ido-ubiquitous` and now I no longer have `ido` completions for `bookmark-jump` (`C-x r b`). I have also tried explicitly adding an override for `bookmark-jump` in `ido-ubiquitous-command-overrides`: 
```elisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
...
 '(ido-ubiquitous-command-overrides
   (quote
    ((disable exact "execute-extended-command")
     (enable prefix "wl-")
     (enable-old prefix "Info-")
     (enable exact "webjump")
     (enable regexp "\\`\\(find\\|load\\|locate\\)-library\\'")
     (disable prefix "tmm-")
     (enable regexp "\\`\\(load\\|enable\\|disable\\|describe\\|custom-theme-visit\\)-theme\\'")
     (enable-old prefix "bbdb-")
     (enable-old exact "where-is")
     (disable exact "todo-add-category")
     (enable exact "find-tag")
     (enable prefix "etags-select-")
     (enable exact "man")
     (enable exact "manual-entry")
     (enable regexp "\\`describe-\\(function\\|variable\\)\\'")
     (enable exact "bookmark-jump") ;; this line is the one of interest
...
)))
```
But to no avail; `bookmark-jump` still no longer uses `ido`.

**Comment by DarwinAwardWinner** [comment]
Can you try enabling `ido-ubiquitous-debug-mode` and `ido-cr+-debug-mode` and then use `bookmark-jump`, and then check your messages buffer for a reason that ido was not used?

Alternatively, you can try the bleeding-edge branch of ido-ubiquitous, which has substantial changes on it. I'm testing it right now, and it gives me ido completion for `bookmark-jump`.

**Comment by ylluminarious** [comment]
@DarwinAwardWinner Ok, I enabled those modes and tried out `bookmark-jump`; found these in the `*Messages*` buffer:
```
ido-ubiquitous: Using override ‘enable’ for function ‘bookmark-completing-read’
ido-completing-read+: Falling back to ‘completing-read-default’ because ido cannot handle COLLECTION being a function (but see `ido-cr+-force-on-functional-collection').
```
Also, thanks for the tip about the bleeding-edge branch; I'll try that out if I can't solve with the main branch first.

**Comment by DarwinAwardWinner** [comment]
Hmm, that looks like a bug. The override should be taking precedence over the no-functional-collection rule.

**Comment by ylluminarious** [comment]
@DarwinAwardWinner Hmm, ok. Any advice on this, then?

**Comment by DarwinAwardWinner** [comment]
I'll have to debug it and release a fix.

**Comment by ylluminarious** [comment]
@DarwinAwardWinner Alright, let me know if you need any more info / testing.

**Comment by ylluminarious** [comment]
@DarwinAwardWinner Hey, just FYI, it appears that the same issue is occurring with `manual-entry`, as well. As you can see in the above code snippet, I also have `ido` explicitly enabled for that command and it was working prior to my upgrading of `ido-ubiquitous`... so I imagine that this is somehow related.

**Comment by ylluminarious** [comment]
@DarwinAwardWinner Sorry to bother you again, but I just noticed that, oddly enough, this is also happening for `Info-` commands, which is also specified in my `ido-ubiquitous-command-overrides`. I also noticed that the following is in `ido-ubiquitous-function-overrides` by default: `(enable exact "bookmark-completing-read")`. So it seems that `bookmark-jump` ought to work fine even without an explicit entry in `ido-ubiquitous-command-overrides`. It appears that all of this is somehow connected to the overrides...

**Comment by ylluminarious** [comment]
@DarwinAwardWinner Well, this is strange and a little embarrassing, but I tried deleting `ido-ubiquitous` and reinstalling and everything seems to be working now... maybe something weird happened when I upgraded. I'll mark this as closed; sorry for the trouble.
