### ISSUE TITLE
Warning (bytecomp): assignment to free variable ‘ido-cur-list’

### ISSUE THREAD

**Issue by tumashu** [DarwinAwardWinner/ido-ubiquitous#121]

**Comment by DarwinAwardWinner** [comment]
This is a known issue: https://github.com/DarwinAwardWinner/ido-ubiquitous#im-getting-some-weird-warnings-from-ido-completing-read-when-emacs-starts

If you can provide steps for me to reproduce this, I can try to investigate.

**Comment by ludwigpacifici** [comment]
Hello @DarwinAwardWinner 

I have the same warning:

```
Compiling file /home/lud/.emacs.d/elpa/ido-completing-read+-20170705.1656/ido-completing-read+.el at Fri Jul  7 19:17:16 2017
Entering directory ‘/home/lud/.emacs.d/elpa/ido-completing-read+-20170705.1656/’

Compiling no file at Fri Jul  7 19:17:16 2017
Warning (bytecomp): value returned from (format "Cannot load %s: %%S" name) is unused
Warning (bytecomp): the function ‘custom-variable-state’ is not known to be defined.
Warning (bytecomp): attempt to inline ‘ido-cr+-active’ before it was defined
Warning (bytecomp): assignment to free variable ‘ido-cur-list’
Warning (bytecomp): reference to free variable ‘ido-cur-list’
```

I used the below `init.el`:

```elisp
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)

(unless package-archive-contents
  (package-refresh-contents))

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)
(setq use-package-verbose t)

(use-package ido
  :ensure t
  :config
  (ido-mode t)
  (ido-everywhere t))

(use-package ido-completing-read+
  :ensure t
  :config
  (ido-ubiquitous-mode 1))
```

Note, `~/emacs.d/elpa/` was empty. So it used the latest version of these packages. Can you please have another look?

**Comment by DarwinAwardWinner** [comment]
Ok, I'll try using this to debug it. Can you tell me which version of Emacs you're using and what OS version?

**Comment by ludwigpacifici** [comment]
I use GNU Emacs from the Git master branch: `GNU Emacs 26.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.16) of 2017-07-04`.

**Comment by DarwinAwardWinner** [comment]
Ok, I tried on Mac OS using using both Emacs 25 and a recent-ish Emacs 26 snapshot, and neither one produced any compile warnings. I tried it with Emacs 24 on Ubuntu 16.10 and did see similar warnings to yours. So maybe it only shows up on Linux for some reason. In any case, I now have a way to reproduce this problem, so I can begin debugging it.

**Comment by DarwinAwardWinner** [comment]
I've just pushed 6f36a3a which should hopefully eliminate these warnings, so wait for MELPA to update and then try the new version. Although last time I tried this, it just caused other people to get different warnings. So we'll see how it works this time.

**Comment by podiki** [comment]
If it helps, I get the warning `Warning (bytecomp): reference to free variable ‘ido-cr+-minibuffer-depth’` when starting up Emacs, but this only started when just now switching from `ido-ubiquitous` to `ido-completing-read+`. I made the package change upon noticing the message about the name change to switch to `ido-completing-read+`. Before that, never had such messages.

**Comment by DarwinAwardWinner** [comment]
As I said in the FAQ, I can't investigate this unless you can tell me how to produce the warning starting from `emacs -Q`.

**Comment by ludwigpacifici** [comment]
Thanks, there are less warnings. Like you said, I see: `Warning (bytecomp): reference to free variable ‘ido-cr+-minibuffer-depth’ ` at each start of Emacs. I created a PR to fix it. Let me know if you are happy with it.

**Comment by podiki** [comment]
Sorry, I haven't been following the tale of these warnings. I was only adding information (that for me at least, this warning only started on changing from ubiquitous to cr+ today) in case it was useful. Before today I never had such warnings under the previous package name.

**Comment by DarwinAwardWinner** [comment]
Ok, I've pushed another change to master that should hopefully fix the warnings about `ido-cr+-minibuffer-depth`. Look for a MELPA update based on git commit 7b71365.

**Comment by podiki** [comment]
Clean loading now, I don't have any warnings! Thanks for the quick work, and the awesome package.

**Comment by mambolevis** [comment]
Hi, I also confirmed that the warning disappeared. Would you mind explaining what was the solution?

**Comment by DarwinAwardWinner** [comment]
The problem is explained in the commit message for https://github.com/DarwinAwardWinner/ido-ubiquitous/commit/7b7136532ee4af0380f667f19700b53853bbbd7a

**Comment by mambolevis** [comment]
Thanks, I got it!
