### ISSUE TITLE
Warning (ido-ubiquitous): The ido-ubiquitous package is now redundant

### ISSUE THREAD

**Issue by mambolevis** [DarwinAwardWinner/ido-ubiquitous#122]
Hi,

I made an update of all my packages and the following message appeared:

`Warning (ido-ubiquitous): The ido-ubiquitous package is now redundant. All functionality, including ido-ubiquitous-mode, has been merged into the ido-completing-read+ package. You should replace ido-ubiquitous with ido-completing-read+ in your Emacs config.`

What is the appropriated configuration right now?

I commented` ido-ubiquitous `and replaced it with `ido-completing-read+`
```
;; (use-package ido-ubiquitous
;;   :ensure t
;;   :config
;;   (ido-ubiquitous-mode +1))
```

```
(use-package ido-completing-read+
  :ensure t
  :config
  (ido-ubiquitous-mode 1))
```
and the following message appeared:
```
Warning (bytecomp): assignment to free variable ‘ido-cur-list’
Warning (bytecomp): reference to free variable ‘ido-cur-list’
```

Thanks

**Comment by DarwinAwardWinner** [comment]
It looks like you have the correct setup. As for the warnings, these are a known recurring issue, as described [here](https://github.com/DarwinAwardWinner/ido-ubiquitous#im-getting-some-weird-warnings-from-ido-completing-read-when-emacs-starts)
