### ISSUE TITLE
Version 4.0 was removed from MELPA?

### ISSUE THREAD

**Issue by ryukinix** [DarwinAwardWinner/ido-ubiquitous#124]
I don't understand, why?

**Comment by DarwinAwardWinner** [comment]
Where does it say that version 4.0 was removed from MELPA? Perhaps you are referring to the fact that ido-ubiquitous was merged into ido-cr+? https://github.com/DarwinAwardWinner/ido-ubiquitous#version-40-changes

**Comment by ryukinix** [comment]
I just cannot found it on emacs. I'm talking about exactly the `ido-cr+`
![image](https://user-images.githubusercontent.com/7642878/28279220-2925df5a-6af6-11e7-9272-ee27f906bc9b.png)

I was using ido-completing-read+ 4.0, but during a debugging section need to remove it. `ad-handle-definition: `ido-completing-read' got redefined` warning.

So then, when I would installing ido-completing-read+ 4.0 back... I just found the 3.6! Weird. Maybe I'm doing something wrong?

**Comment by ryukinix** [comment]
I removed again, call `package-refresh-contents`, but nothing. I tried installing in another machine (a remote server) and, yes, the version 4.0 is on MELPA. But why doesn't show on my computer? You know something I can do to rebuild melpa cache or something like that?

**Comment by ryukinix** [comment]
Sorry for the mess. I fixed. In my user-init profile I forgot that I pinned the `ido-completing-read+` to `melpa-stable`.
