### ISSUE TITLE
Does ido-ubiquitous make ido-everywhere unnecessary?

### ISSUE THREAD

**Issue by tarsius** [DarwinAwardWinner/ido-ubiquitous#63]
The readme isn't clear on that point.

> Does what you were really hoping for when you did `(setq ido-everywhere t)`.

Only tells me that `ido-ubiquitous` causes ido completion to be used *even more* - not whether that includes what `ido-everywhere` provides or whether one gets the most ido completion by enabling *both* modes.

**Comment by DarwinAwardWinner** [comment]
No, you have to enable both. They're actually dealing with two separate things. `ido-everywhere` deals with buffer and file completion, while ido-ubiquitous deals with replacing `completing-read`.

**Comment by tarsius** [comment]
Thanks!

**Comment by hariharanr5** [comment]
@tarsius Thanks for asking. @DarwinAwardWinner Does this mean i have to have both
(ido-ubiquitous-mode t) and (ido-everywhere t) in my init.el? Having a simple configuration in the readme will be helpful for noobs like me.

**Comment by DarwinAwardWinner** [comment]
Yes, that's correct. I'll consider adding a utility function to enable all ido features that can possibly be enabled (off the top of my head: ido, ido-everywhere, ido-ubiquitous, magit ido completion, org ido completion, smex)

**Comment by tarsius** [comment]
I think it would be better to add the code which does that to the documentation instead of providing a function to do it.

**Comment by DarwinAwardWinner** [comment]
That would be a hefty chunk of code once you put in all the checks for packages that may or not be loaded/installed.

**Comment by tarsius** [comment]
Ah well, since a user of `ido-ubiquitous` likely wants "all things ido", a function might not be such a bad idea after all. The reason why I suggested putting it into the documentation was, that this would also serve to tell the user what to install. Then again you can just put that into the documentation as a simple list - "if you like this, you might also like...".

**Comment by DarwinAwardWinner** [comment]
I'll leave this issue open until I've added the "enable all the ido" function.
