### ISSUE TITLE
Restructure to facilitate use as a library by other packages?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [DarwinAwardWinner/ido-ubiquitous#64]
Magit wants to use ido-ubiquitous' completion for their ido completion due to the extra fixes it provides: https://github.com/magit/magit/pull/1750. Currently this is a pain in the ass for anyone attempting to do it. I should consider how to cleanly separate "ido fixes" from "ido-ubiquitous functionality" to make this kind of thing easier.

**Comment by DarwinAwardWinner** [comment]
@tarsius I would appreciate your input here.

**Comment by tarsius** [comment]
Yes, that would be great. I hope that eventually these fixes will make it into `ido.el` and first separating the fixes from the additional features seems the way to go. Even if the fixes later are not accepted. It would probably be a good idea for the two parts are implemented as two separate libraries (but which can live in the same repository as far as I am concerned).

**Comment by DarwinAwardWinner** [comment]
Maybe what I will do is turn `completing-read-ido` into just a completion function that uses ido whenever possible and doesn't depend on whether ido-ubiquitous is enabled (though it will still respect overrides, because otherwise it would break stuff). Then I will make a new function `completing-read-ido-ubiquitous` that wraps `completing-read-ido` and checks the value of `ido-ubiquitous-mode`. I'll give this some more thought over the weekend.

**Comment by DarwinAwardWinner** [comment]
@tarsius, I like your idea of putting the ido fixes which should always be enabled in a separate library. I think I'll also take advantage of the restructuring to rename ido-ubiquitous to something [less confusing](https://github.com/DarwinAwardWinner/ido-ubiquitous/issues/63). The name change will also allow me to break backwards compatibilty, which will probably be necessary to implement this.

**Comment by DarwinAwardWinner** [comment]
I've received word that the ido maintainer is receptive to merging any relevant improvements, so I'll make sure to pursue that when the time comes.

**Comment by DarwinAwardWinner** [comment]
Hey @tarsius, I've taken a first stab at separating out the ido fixes from ido-ubiquitous. I've created a new branch "refactor" in which there is now a new file `ido-completing-read+.el` which implements a function called `ido-completing-read+`. This file should be completely independent from ido-ubiquitous and all the names have been changed, so it should even coexist peacefully with the current version of ido-ubiquitous. There's still a some cleanup and documentation to do, but I would appreciate it if you could try this out as the backend for magit's ido completion and let me know if you encounter any problems.

**Comment by DarwinAwardWinner** [comment]
Oh yeah, and if you have a better suggestion for the name, please do share.

**Comment by DarwinAwardWinner** [comment]
@tarsius Somewhat surprisingly, I'm actually almost ready to release this and a simpler version of ido-ubiquitous built on top of it. I still need to dogfood it for a little while to put it through its paces, but we can start talking now about how to synchronize releases so as not to break magit. I'm thinking that I can release ido-completing-read+ first, then you can update magit to rely on it, and then finally I can wait a little while and release the new ido-ubiquitous since magit will no longer depend on the old one. That way there's no need to update simultaneously and risk race conditions.

**Comment by tarsius** [comment]
I actually intend to work on magit's ido support too tomorrow, so the timing is perfect :-)

**Comment by tarsius** [comment]
Uh, just released that this sounds like "get this done tomorrow" - what I intended to say is what I actually said "I will work on it" and (which I didn't say) "I don't expect that will be the end of it" :-)

**Comment by DarwinAwardWinner** [comment]
Ok, pretty much all you need to do is `(require 'ido-completing-read+)`, then go back to the old coded that doesn't use ido-ubiquitous and replace `ido-completing-read` with `ido-completing-read+`. Note that this doesn't give you old-style default mode (that's an ido-ubiquitous specific feature).

Alternatively, if you do want to use overrides to allow some commands to use old-style default selection, you can use the new function `completing-read-ido-ubiquitous` from the new ido-ubiquitous package. I've changed it so it doesn't check whether the mode is enabled any more, it just assumes that if it's being called, ido completion is wanted. Then have magit add the appropriate overrides after loading ido-ubiquitous (and I will remove/fix the magit overrides built in to ido-ubiquitous to avoid conflicts).

If you want to chat live and be able to ask questions as they come up instead of playing ping pong on Github, let me know your preferred chat network and I'll connect with you there.

**Comment by DarwinAwardWinner** [comment]
Actually, it looks like the situation is even better. I've just added a function alias from `completing-read-ido-ubiquitous` to `completing-read-ido`, which means that the current magit code should work with the new version of ido-ubiquitous unmodified. All the workarounds you've put in to make the old version will now simply have no effect, except for let-binding `ido-ubiquitous-next-override`, which retains its usual meaning. If true, then I can update ido-ubiquitous at any time without breaking magit's current code, and then afterward you can merge whatever changes you want to make, and there would be no need for synchronized updates. I still need to kick the tires on the new version before releasing it, and I'll make sure it doesn't break magit before releasing as well. But this makes things a lot simpler.

**Comment by DarwinAwardWinner** [comment]
Also, when you do update your code, note that the next release of ido-ubiquitous and the first release of ido-completing-read+ will both be version 3.0 (they will always have the same version from now on).

**Comment by tarsius** [comment]
> If you want to chat live and be able to ask questions as they come up instead of playing ping pong on Github, let me know your preferred chat network and I'll connect with you there.

I have nothing sane configured right now, so let's use https://gitter.im/magit/magit.

**Comment by tarsius** [comment]
Am I missing something obvious, or is this a bug?

```lisp
(let ((ido-ubiquitous-next-override 'enable-old))
  (completing-read-ido-ubiquitous ": " '("a" "b" "c")))
;; C-x C-e RET => "a"

(progn
  (defun foo (prompt collection)
    (let ((ido-ubiquitous-next-override 'enable-old))
      (completing-read-ido-ubiquitous prompt collection)))
  (foo ": " '("a" "b" "c")))
;; C-x C-e RET => ""
```

**Comment by DarwinAwardWinner** [comment]
Both of those return empty strings as expected for me. Note that just having an empty input isn't enough to trigger the "old-style" mode. It only triggers if RET or C-j is the first thing you press. Basically, all it does is swap the function of RET and C-j on the first keypress only.

Also, I created https://gitter.im/DarwinAwardWinner/ido-ubiquitous in case you don't want to pollute the magit channel with ido-ubiquitous specific stuff.

**Comment by tarsius** [comment]
I forgot to say: the next magit release will require emacs 24.2.

**Comment by npostavs** [comment]
> If I am not mistaken magit currently only has one command which requires that "" is returned for emtpy input. The second prompt of magit-branch-set-upstream: "Change upstream to branch (empty to unset)". So I am just gonna wrap that with (let ((ido-ubiquitous-next-override 'enable-old)) ...) and not use that anywhere else.

I'm still of the opinion that this command shouldn't use the old style. Unsetting doesn't feel like a default, so hitting `C-j` rather than `RET` to choose it makes more sense to me.

**Comment by DarwinAwardWinner** [comment]
By the way @tarsius, don't forget to add `(ido-ubiquitous "3.0")` to magit's package dependencies.

**Comment by tarsius** [comment]
@DarwinAwardWinner No, that would mean that everyone would have to install ido-ubiquitous, even those that don't use ido. Instead I mention this dependency in the doc-string, and since most users will overlook that, also as a warning when the turn on ido completion without installing the dependency.

**Comment by tarsius** [comment]
@npostavs I have added a separate `magit-branch-unset-upstream`,
@DarwinAwardWinner which also means that magit now only requires `ido-completing-read+`.

**Comment by tarsius** [comment]
By the way, my draft can still be found here https://github.com/magit/magit/compare/ido-completing-read-plus?expand=1.

**Comment by tarsius** [comment]
I won't be near a computer the next few days. Please delay the release until I am back (only if it would break Magkt's next branch of course).

**Comment by DarwinAwardWinner** [comment]
As far as I can tell, there's no need for simultaneous releases after all, especially now that you're using `ido-completing-read+`. I just need to release ido-ubiquitous (and id-cr+) 3.0 before you release the magit version the depends on it. Which I will most likely do today or tomorrow.
