### ISSUE TITLE
Fix free variable warning

### ISSUE THREAD

**Issue by kaushalmodi** [DarwinAwardWinner/ido-ubiquitous#68]
Can you initialize `ido-ubiquitous-debug-mode` to `nil` to prevent these warnings?
For now, I have added it to `:preface` of `use-package` to get rid of those.

```
~/.emacs.d/elpa_25_0/ido-ubiquitous-20150410.251/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa_25_0/ido-ubiquitous-20150410.251/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa_25_0/ido-ubiquitous-20150410.251/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa_25_0/ido-ubiquitous-20150410.251/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
```

**Comment by kaushalmodi** [comment]
But I am unable to get rid of these warnings:

```
~/usr_local/apps/emacs/25.0/share/emacs/25.0.50/lisp/ido.elc:Warning:
    reference to free variable `ido-cr+-enable-next-call'
~/usr_local/apps/emacs/25.0/share/emacs/25.0.50/lisp/ido.elc:Warning:
    reference to free variable `ido-cr+-replace-completely'
```

**Comment by DarwinAwardWinner** [comment]
Hmm. First of all, I didn't realize that MELPA was tracking my bleeding edge branch and not my master branch. I'll have to get that fixed. Second, in the latest version I have already added a `defvar` for the debug mode variable to the beginning of the file ([here](https://github.com/DarwinAwardWinner/ido-ubiquitous/commit/7239d809fc94b6024b5e50571c9b3204cbff4a03#diff-3aae4bfbdbe9bf33920a3bcd68cbd451R87)), so it shouldn't produce that warning any more, once MELPA picks up the new version. For the other warnings, I'm not quite sure how to fix those, because Emacs is reporting them as coming from `ido.elc`, which is obviously wrong.

**Comment by kaushalmodi** [comment]
Yeah, but they got fixed by putting defvars before `(package-initialize)`

**Comment by DarwinAwardWinner** [comment]
FYI, ido-ubiquitous in MELPA is probably going to get downgraded back to the previous version soonish, because I submitted a pull request for MELPA to track master and not bleeding-edge. You might have to restart emacs after that downgrade.

**Comment by kaushalmodi** [comment]
Sure. Thanks for the prompt fix.

**Comment by DarwinAwardWinner** [comment]
Ok, I am pushing ido-ubiquitous 3.0 to master for real this time, which means it should soon show up in MELPA. Please report any errors you encounter.

**Comment by zhiyuanshi** [comment]
Thanks @DarwinAwardWinner. I stumbled into this post since I was also looking for a way to inhibit those messages.

**Comment by DarwinAwardWinner** [comment]
Is anyone still seeing any of the above messages? If so, please post the message you get, and under what circumstances you get it, including your OS version and Emacs version.

**Comment by zhiyuanshi** [comment]
GNU Emacs 24.4.1
OS X 10.10.3

When I invoke `emacsclient` via `emacsclient --create-frame --no-wait --alternate-editor=''`. Thanks @DarwinAwardWinner!

Messages:
```
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    reference to free variable `ido-ubiquitous-debug-mode'
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    assignment to free variable `ido-context-switch-command'
~/.emacs.d/elpa/ido-ubiquitous-20150423.1037/ido-ubiquitous.elc:Warning:
    assignment to free variable `ido-context-switch-command'
```

**Comment by DarwinAwardWinner** [comment]
Ok, do you see that message *every time*, even when your emacs daemon is already running? Does it matter whether emacs is running as a daemon vs a normal GUI emacs with a running server? Does it matter whether you already have an emacs frame open when you invoke emacsclient? Does it happen when you start emacs in non-daemon mode?

**Comment by kaushalmodi** [comment]
I put these lines in my init before doing `(require 'package)`.

```el
(defvar ido-cr+-enable-next-call   nil)
(defvar ido-cr+-replace-completely nil)
```

If I don't have these, I get the free variable warnings when I launch emacsclient with no frames/emacs process running to begin with (not emacs daemon, can't run that due to some linux limitation. But I run the server in my init). These warnings **don't appear in non-daemon emacs**.

**Comment by kaushalmodi** [comment]
The same applies to `ido-context-switch-command` except that I can add its defvar declaration after requiring package; currently I have it this way using `use-package`:

```el
(use-package ido
  :preface
  (progn
    ;; `defvar's to prevent compile warnings
    (defvar ido-cur-item               nil)
    (defvar ido-default-item           nil)
    (defvar predicate                  nil)
    (defvar inherit-input-method       nil)
    (defvar ido-cur-list               nil)
    (defvar ido-context-switch-command nil))
    ;; more stuff
```
[Full ido setup][1]
[1]: https://github.com/kaushalmodi/.emacs.d/tree/a96103dcdea5c1b144a2e4edb2794aa9f42379b8/setup-files/setup-ido.el#L7-L16

**Comment by zhiyuanshi** [comment]
@DarwinAwardWinner I only see the message when Emacs is starting up (no matter it's daemon or normal GUI Emacs). Therefore, for normal GUI Emacs, I see the same messages in the Compile-Log buffer. Similarly, if the daemon is already running and I fire another `emacsclient`, I won't see the messages in the shell (since the daemon is already there).

**Comment by DarwinAwardWinner** [comment]
Is this fixed in the latest master?

**Comment by jacksonrayhamilton** [comment]
I was seeing these errors in `*Compile-Log*` after starting the daemon. After updating they no longer appear.

**Comment by DarwinAwardWinner** [comment]
I'm going to assume this is fixed unless I hear otherwise.

**Comment by cpitclaudel** [comment]
@kaushalmodi 

> The same applies to ido-context-switch-command and ido-ubiquitous-debug-mode except that I can add its defvar declaration after requiring package; currently I have it this way using use-package:

> ```
(use-package ido
  :preface
  (progn
    ;; `defvar's to prevent compile warnings
    (defvar ido-cur-item               nil)
    (defvar ido-default-item           nil)
    (defvar predicate                  nil)
    (defvar inherit-input-method       nil)
    (defvar ido-cur-list               nil)
    (defvar ido-context-switch-command nil))
    ;; more stuff
```

Uh, I'd be very careful with this: in particular, with `defvar predicate`. You're essentially making `predicate` a special variable, which will break any code that uses lexical scoping to close over a predicate locally called `predicate`, won't it? At least this seems to be biting users of Flycheck at https://github.com/flycheck/flycheck/issues/574

**Comment by kaushalmodi** [comment]
@cpitclaudel Apologies if my `use-package` snippet was the source of confusion and frustration for Flycheck users. I have added a warning note in that comment to try to prevent further propagation of this.

*I do not use Flycheck and I have stopped using ido altogether. So I cannot confirm this issue.*

**Comment by cpitclaudel** [comment]
@kaushalmodi No problem at all :) Thanks for updating the snippet.
