### ISSUE TITLE
package-install is not working

### ISSUE THREAD

**Issue by tprk77** [DarwinAwardWinner/ido-ubiquitous#70]
Not sure if this is the best place to put this issue, but here goes...

Trying to install `ido-ubiquitous` with a `package-install` from Melpa is not working. The message is "package-compute-transaction: Package `ido-completing-read+-3.0' is unavailable".

The backtrace looks like this:

    Debugger entered--Lisp error: (error "Package `ido-completing-read+-3.0' is unavailable")
      signal(error ("Package `ido-completing-read+-3.0' is unavailable"))
      error("Package `%s-%s' is unavailable" "ido-completing-read+" "3.0")
      package-compute-transaction((ido-ubiquitous) ((emacs (24 1)) (ido-completing-read+ (3 0))))
      package-install(ido-ubiquitous)

Maybe you just need to remove `ido-completing-read+` from the `Package-Requires`?

    ;; Package-Requires: ((emacs "24.1") (ido-completing-read+ "3.0"))

**Comment by DarwinAwardWinner** [comment]
I just split part of ido-ubiquitous into a separate library called ido-completing-read+. As such, ido-ubiquitous now depends on that library. I'm guessing that MELPA indexed the updated ido-ubiquitous before it indexed the newly-released ido-completing-read+. Hopefully it should be fixed shortly.

**Comment by tprk77** [comment]
That's pretty funny. Now I see the commit, and it was only an hour ago! I guess I hit it at just the wrong moment. Hey by the way, I really like this extension, nice work.

**Comment by tprk77** [comment]
Yep, it is working now.
