### ISSUE TITLE
Broken on Emacs 24.3

### ISSUE THREAD

**Issue by omajid** [DarwinAwardWinner/ido-ubiquitous#71]
ido-ubiquitous uses `define-error`. This is missing in Emacs 24.3, making a recent update to ido-ubiquitous break a lot of functionality completely (eg, when smex is used, or when I hit `C-h f`). I get an error `symbol's function definition is void: define-error`.

Please add compatibility for (slightly) older versions of emacs. Something like this, maybe: 
http://emacs.stackexchange.com/questions/3905/define-error-for-older-emacs

**Comment by DarwinAwardWinner** [comment]
Thanks for reporting! This should be fixed now.

**Comment by omajid** [comment]
Thanks for the quick fix!
