### ISSUE TITLE
Selecting nothing at an ido prompt

### ISSUE THREAD

**Issue by purcell** [DarwinAwardWinner/ido-ubiquitous#74]
With `auto-insert-mode` enabled, creating a new `.el` file prompts for information to insert into the fresh elisp boilerplate. The `Keywords` prompt uses `ido`, and entering nothing (just hitting `RET`) signifies that you are done entering keywords.

Up until the recent `ido-ubiquitous` changes (I believe), it was possible to do this with `ido-ubiquitous-mode` enabled. Now, the first completion is forcibly selected in response to empty input, so it's not possible to finish entering keywords.

This therefore seems like a minor regression.

**Comment by DarwinAwardWinner** [comment]
Previously, I had the default override mode set to old-style default selection while I waited for more overrides to be added, but I changed it to normal mode in the latest release. Can you try customizing `ido-ubiquitous-function-overrides` and adding `auto-insert` to it with "Enable ido-ubiquitous in old-style default mode" and let me know if that fixes it?

**Comment by purcell** [comment]
Hmm. Tried that:

```
(push '(enable-old exact "auto-insert") ido-ubiquitous-function-overrides)
```

but same result. :-/

**Comment by DarwinAwardWinner** [comment]
You have to use `M-x customize`. It does the work of defining the advice on all the functions.

**Comment by DarwinAwardWinner** [comment]
I suppose I could add some macros to automate this, though.

**Comment by purcell** [comment]
Ah yes, that works. I guess that if it's exposed via `customize`, there probably needs to be a programmatic way to set it too, even if it's just some sort of `reapply` function.

**Comment by purcell** [comment]
Thanks Ryan.

**Comment by DarwinAwardWinner** [comment]
There is `ido-ubiquitous-apply-function-override` for functions. There is currently no analog for commands, so I will add that.

**Comment by purcell** [comment]
Great, thanks.
