### ISSUE TITLE
void-variable choices

### ISSUE THREAD

**Issue by yashi** [DarwinAwardWinner/ido-ubiquitous#75]
Hi,

Just installed ido-ubiquitous from melpa and I see the following backtrace:
```
Debugger entered--Lisp error: (void-variable choices)
  (remove def choices)
  (cons def (remove def choices))
  (setq choices (cons def (remove def choices)) def nil)
  (progn (setq choices (cons def (remove def choices)) def nil))
  (if (and def initial ....
  (let ((initial (or ....
  (condition-case sig (progn (cond ....
  (let ((orig-args (list prompt ....
  ido-completing-read+....
```

A quick look at `ido-completing-read+`, this happens when def is given AND it's not a list.  Is this my bad usage?  I read a comment stating that ido has a bug to provide initial input and def.

Thanks.

**Comment by DarwinAwardWinner** [comment]
Whoops, this is a mistake because ido calls the second argument "choices" while `completing-read` calls is "collection". In a recent update I changed the argument to match `completing-read` but forgot to change that bit of code.

**Comment by yashi** [comment]
The current head indeed fixed my problem.  Thanks.
