### ISSUE TITLE
Can't  create a new contact in bbdb

### ISSUE THREAD

**Issue by magichowl** [DarwinAwardWinner/ido-ubiquitous#79]
see 
<http://savannah.nongnu.org/bugs/?45178>

When I'm creating a new contact and prompted for "Snail Mail Address Label [RET when done]", if I enter the key "Enter", then the loop "Street, line N" begins, even I enter an empty string. If I enter a space, then I would be prompted for "Phone Label [RET when done]".

It seems the input for the prompt contains words "[RET when done]" malfunctions.

The fresh emacs configuration don't have this bug.

Later I found the problem:

(require-package 'ido-ubiquitous)
(ido-ubiquitous-mode t))

A workaround is to comment the above lines. 

However, this is not a desire solution, do u know what's wrong?

**Comment by DarwinAwardWinner** [comment]
I'm not familiar with the usage of bbdb, so you're going to need to tell me what command you are running that shows this bug. If you're running the command from a keyboard shortcut, try pressing `C-h k` and then typing the keyboard shortcut, and it will tell you which command it is calling. Most likely you will need to add an override for this command in `ido-ubiquitous-command-overrides`.

**Comment by magichowl** [comment]
use command "M-x bbdb-create", the minubuffer would prompt fields "Name: ",
"Organization: ", "E-Mail Addresses: " for insertion,

after that, "Snail Mail Address Label [RET when done]: ", at this point, several candidates
says, "{home | work | other}" is provided by ido-ubiquitous,
if no string is entered or one candidate (say, "home") is entered, the
flow would in a loop by prompting:

"Street, line 1"

"Street, line 2"

"Street, line 3"
...

When ido-ubiquitous is disabled, the flow would continues normally.



A strange thing is, if "space" is entered for "Snail Mail Address Label [RET when done]: ", the flow of field insertion continues normally.

**Comment by DarwinAwardWinner** [comment]
Ok, bbdb uses the old deprecated way of specifying defaults, which means that ido-ubiquitous needs to be told about that by adding an override. Customize the variable `ido-ubiquitous-command-overrides` and add "bbdb-" as a prefix match in old-style default mode (which will swap the behavior of C-j and RET on an empty input). I will add this override to the defaults for the next version.

**Comment by magichowl** [comment]
ido-ubiquitous: Unknow match spec type "prefic". See `ido-ubiquitous-spec-matches' for valid types

**Comment by DarwinAwardWinner** [comment]
I made a typo, but I fixed it again. If you're updating from MELPA, it'll take a little while before it updates.
