### ISSUE TITLE
Unknown match spec type "prefic"

### ISSUE THREAD

**Issue by mrkkrp** [DarwinAwardWinner/ido-ubiquitous#81]
Hi, after a recent update from MELPA, when I start Emacs I see the following thing in the minibuffer:

> ido-ubiquitous: Unknown match spec type "prefic". See `ido-ubiquitous-spec-matchers' for valid types.

And this thing seems to block Emacs entirely! I had to `killall emacs` and use `nano` to comment out everything related to `ido-ubiquitous`. It seems like this `"prefic"` is just a typo.

**Comment by hariharanr5** [comment]
This issue has been fixed now. See https://github.com/DarwinAwardWinner/ido-ubiquitous/pull/80

**Comment by mrkkrp** [comment]
Oh, I think I just have to wait till next MELPA build. Thanks! Closing it.

**Comment by DarwinAwardWinner** [comment]
This does raise another issue, which is that ido-ubiquitous should just ignore invalid overrride spec, not crash on them.
