### ISSUE TITLE
Ignoring default value for `where-is`

### ISSUE THREAD

**Issue by egarrulo** [DarwinAwardWinner/ido-ubiquitous#83]
Calling `C-h w (where-is)` when point is on the name of a function, causes the minibuffer prompt to show such function as the default value, whilst IDO selects a different default.

Tested on Emacs 24.5.1 and IDO Ubiquitous 3.3.

Thanks for your attention.

**Comment by DarwinAwardWinner** [comment]
Yes, I just noticed this yesterday. I need to add an override for using old-style default mode for this function.

**Comment by DarwinAwardWinner** [comment]
Note: `where-is` was fixed to use the default argument a few years ago, so the override is being changed accordingly.

https://github.com/emacs-mirror/emacs/commit/3829bcc589bf84c5b2f7327d8728c4f84840829b
