### ISSUE TITLE
References and assignments to free variables

### ISSUE THREAD

**Issue by mrkkrp** [DarwinAwardWinner/ido-ubiquitous#84]
I don't know if it's some changes in Emacs trunk or in `ido-ubiquitous` itself, but now anytime I start Emacs I'm presented with contents `*Compile-Log*` buffer. Here it is:

```
Warning (bytecomp): reference to free variable `ido-cr+-enable-next-call'
Warning (bytecomp): reference to free variable `ido-cr+-replace-completely'
Warning (bytecomp): assignment to free variable `ido-context-switch-command' [2 times]
Warning (bytecomp): reference to free variable `ido-ubiquitous-debug-mode' [12 times]
Warning (bytecomp): assignment to free variable `ido-context-switch-command' [2 times]
```

I have to switch to the log buffer and *manually hide it every time*. Can you `defvar` these variables or something?

I've seen [this issue](https://github.com/DarwinAwardWinner/ido-ubiquitous/issues/68), but collection of variables and the messages are a bit different, so I decided to open separate issue.

P.S. `ido-ubiquitous` is installed from MELPA, Emacs 25.0.50.12 is built from repo.

**Comment by DarwinAwardWinner** [comment]
I figured out how to fix the warnings about `ido-context-switch-command`, but I have no idea where those other warnings are coming from, because those other three variables are all properly declared using `defvar` or `defcustom`.

**Comment by mrkkrp** [comment]
I've just upgraded `ido-completing-read` and `ido-ubiquious` from MELPA, but collection of warnings remains the same. I will see if I can understand on my own why I see them. There should be a reason for it, because I'm using many packages and other packages don't produce any warnings.

**Comment by DarwinAwardWinner** [comment]
ido-ubiquitous hooks kind of deep into Emacs' innards and tends to run into a lot of weird edge cases as a result.

**Comment by mrkkrp** [comment]
Strange, flycheck highlights `(require 'ido)` and reports two former warnings (ido itself is built-in, right? not sure why this happens). `ido-context-switch-command` are reported for `(require 'ido-completing-read+)`... I'm not sure if my guess is valid, but maybe it's because of autoloads. If you open autoloads for `ido-completing-read+`, you will see that if Emacs just loads autoloads, these variables are mentioned there, while `defvar`s not. It's in advice for `ido-completing-read`. What do you think?

**Comment by mrkkrp** [comment]
Indeed, when I comment out the advice for `ido-completing-read` (only in audoloads) the warnings are gone. Maybe it won't hurt to autoload `defvar`s too?

**Comment by DarwinAwardWinner** [comment]
Autoloads! My only weakness! 

I think you're right. I'll add autoloads for all the variables mentioned in your initial report.

**Comment by DarwinAwardWinner** [comment]
Please reopen if you see any more byte compile warnings (or open a new issue if they're unrelated).

**Comment by mrkkrp** [comment]
This worked! All the warnings are gone, except for this one:

```
Warning (bytecomp): assignment to free variable `ido-context-switch-command' [4 times]
```

Is it possible that this variable is assigned before it's `defvar`ed? This would explain the situation.

**Comment by mrkkrp** [comment]
Wait, I'm using several ido-related packages. Maybe it's not because of yours. I need to investigate it thoroughly.

**Comment by mrkkrp** [comment]
If I remove `ido-ubiquitous` the warning is not reported. It certainly has something to do with `ido-completing-read+` package.

**Comment by mrkkrp** [comment]
This should be reopened, perhaps, but I don't see "Comment and reopen" button this time. Interestingly, if I put this before package initialization:

```
(defvar ido-context-switch-command)
```

The warning is still there. If I add some value:

```
(defvar ido-context-switch-command nil)
```

The message is gone. I don't know if it's safe to autoload the second version of `defvar`. My guess is that `defvar`ed variables without value cannot (should not) be assigned to.

There are possibility to add a hook that will be invoked after initialization and hide `*Compile-Log*` window, but I don't think this is correct solution because this way some important messages will be automatically hidden too. What do you think?

**Comment by PythonNut** [comment]
I'm seeing this too on `Emacs 25.0.50`.

**Comment by DarwinAwardWinner** [comment]
This seems possibly relevant: http://lists.gnu.org/archive/html/bug-gnu-emacs/2012-11/msg01055.html

> This is not a new problem, actually.  Even if it didn't happen earlier,
> it's not because byte-compiler's warnings have changed, but because
> some change either causes a code to be byte-compiled which wasn't before.
> 
> My guess is that the changes in advice.el have as a side consequence
> that your advice now gets compiled even before info.el is loaded.

**Comment by mrkkrp** [comment]
What does `ido-context-switch-command` actually mean? It has no doc string, it seems. Even if it's `nil`, everything works as usual, or there is some edge cases that I don't know about?

**Comment by DarwinAwardWinner** [comment]
It's used to implement switching between file and bigger modes, but I've co-opted it to implement falling back to non-ido completion. I believe it is only ever bound using `let`.

**Comment by mrkkrp** [comment]
Well, I see only two solutions:

1. Autoload `(defvar ido-context-switch-command nil)`, if you think it's safe;

2. Users must deal with this on their own, because there is nothing conceptually wrong with your package. I've added `(setq ido-context-switch-command nil)` to my config and I've not been experiencing any problems so far. Maybe you could add a note about this warning in `README.md` file.

**Comment by DarwinAwardWinner** [comment]
In this case, I believe it is save to initialize it to nil or, for that matter, anything at all, because I'm about 80% sure that ido only ever reads its value while it is let-bound, so its actual initial value is completely irrelevant. But that's only 80% because analyzing dynamically-scoped variables is hard, which is probably why Emacs is issuing that warning in the first place.

**Comment by mrkkrp** [comment]
If so, I think it's a good idea to push necessary changes into the repository. Even we are wrong, someone will open an issue sooner or later, and then you can just revert the changes.
