### ISSUE TITLE
find-function xref-find-definition are not triggering ido

### ISSUE THREAD

**Issue by vspinu** [DarwinAwardWinner/ido-ubiquitous#85]
Hi. This is emacs 25.0.50. Adding to `ido-ubiquitous-command-overrides` doesn't help.

**Comment by vspinu** [comment]
After a restart `find-function` started working. `xref-find-...` functions still don't work.

**Comment by vspinu** [comment]
Other functions are also not working as well. For example gnus functions are not getting ido (like `gnus-summary-copy-article`).  

I used to have my own advice around `completing-read` and all was fine. Now I try to switch to `ido-ubiquitous` but it's not really doing what it adverts.

**Comment by DarwinAwardWinner** [comment]
It looks like gnus has its own customization for which completing read function to use, just like org-mode and magit, so you'll have to customize that separately. Try `M-x customize-variable gnus-completing-read-function`. I'll update the readme to note this.

**Comment by DarwinAwardWinner** [comment]
As for the xref function, I assume you are referring to this elisp package? https://github.com/ellerh/xref 

If so, I can't even get that to load in my emacs (24.4.1). It says "Given parent class eieio-singleton is not a class". But reading the code, I see it uses `(tags-lazy-completion-table)` as the collection argument, which returns a function. A functional collection can be used to implement a completely different style of completion, or it can just use normal completion, but ido-ubiquitous can't tell the difference, so it avoids using ido completion in this case unless you add a specific override to tell it that it's ok. (You should hopefully be able to see this by turning on `ido-ubiquitous-debug-mode` and seeing it explain why it decided not to run. Check the messages buffer.) You can try adding `(enable prefix "xref-")` to `ido-ubiquitous-command-overrides` to see if it works ok. If so, please let me know and I'll add that override to the defaults.

**Comment by vspinu** [comment]
> As for the xref function, I assume you are referring to this elisp package? https://github.com/ellerh/xref

Yes. It's new generic interface for cross reference navigation in emacs 25.

>  You should hopefully be able to see this by turning on ido-ubiquitous-debug-mode and seeing it explain why it decided not to run.

It actually runs it with `(enable prefix "xref-")`

```
Ido-Ubiquitous-Debug mode enabled
ido-ubiquitous: Using override `enable' for command `xref-find-definitions'
```

**Comment by vspinu** [comment]
> so it avoids using ido completion in this case unless you add a specific override to tell it that it's ok.

I would like to tell `ido-ubiquitous` to do exactly the opposite - trigger itself everywhere unless I specify otherwise. Is this possible?

**Comment by DarwinAwardWinner** [comment]
For the functional collection issue, you can customize `ido-ubiquitous-allow-on-functional-collection`. You can also set `ido-cr+-max-items` to nil to disable the large collection fallback. I believe that will leave overrides as the only thing that would disable ido-ubiquitous.

**Comment by vspinu** [comment]
>  you can customize ido-ubiquitous-allow-on-functional-collection

Sounds good. Any known caveats except those disabled in overrides?

> ido-cr+-max-items to nil to disable the large collection fallback

Ok. This was it. xref now works. Even without `(enable prefix "xref-")`. 

Thanks.

**Comment by DarwinAwardWinner** [comment]
All the known ones are included in the default overrides. If you're going to enable that, I'd appreciate if you could report any new ones you find, so I can add overrides for them as well.

**Comment by vspinu** [comment]
Sure. I will do that.

**Comment by dgutov** [comment]
@DarwinAwardWinner I don't think you should include `xref-` in the overrides. While the built-in completion tables used by elisp and etags xref backends are relatively simple, there's no reason to believe that all xref backends will behave so.

**Comment by DarwinAwardWinner** [comment]
@dgutov Ok, I will remove the xref override. Sorry I missed this comment for a while. (Your comment in #104 prompted me to find it.)

**Comment by dgutov** [comment]
@DarwinAwardWinner Thanks.
