### ISSUE TITLE
Better documentation of overrides

### ISSUE THREAD

**Issue by vspinu** [DarwinAwardWinner/ido-ubiquitous#86]
Would be nice to add a couple of words to the readme about how ido-ubiquitous works internally, how it handles `completing-read` and what are those `overrides`.

After reading the documentation of `overrides` I am still confused of what are the `enable` settings for. Isn't it the case that `ido-ubiquitous` makes all `completing-read` calls behave like ido? So that you would need only `disable` overrides?

**Comment by DarwinAwardWinner** [comment]
Completing-read is a complicated function with a lot of esoteric options and backward-compatibility quirks, and ido doesn't support all of them. And worse, it's not always possible to tell from the argument list whether an ido incompatible feature is being used or not. So when it detects a combination of arguments that *might* possibly use a feature that ido doesn't support, it turns off ido for that completion event, unless you add an override to tell it that it's ok. 

(Another unrelated use is that if you just want to force ido completion on a specific set of commands, you can set the default to disable and use overrides to enable the specific commands you want.)

Anyway, this information is all contained in bits and pieces in the docstrings of the ido-ubiquitous package, but I agree it would be good to have it all in one place, so I will add some information about this to the readme when I get a chance.

**Comment by vspinu** [comment]
> and ido doesn't support all of them.

Aha. I see. Thanks.

I have been using a very simple advice like: 
```
(let ((allcomp (all-completions "" collection predicate)))
	(if allcomp
	    (ido-completing-read prompt	;;  allcomp
				 (delete "." (delete "" allcomp))
				 nil require-match initial-input hist def)
	  (funcall orig prompt collection predicate require-match initial-input hist def)))
```

and it all worked pretty smoothly everywhere (gnus, xref, you name it).  I understand that this is a brute force, but it did the job pretty well. I wonder if an user option like `ido-ubiquitous-force-everywhere` that would do something similar irrespective of `completing-read` quirks.

**Comment by DarwinAwardWinner** [comment]
The goal of ido-ubiquitous is to enable ido in as many places as possible without breaking things. So there's no one specific option for that, but I believe it is possible with a combination of options, as I noted in my other comment: https://github.com/DarwinAwardWinner/ido-ubiquitous/issues/85#issuecomment-114593910
