### ISSUE TITLE
Duplicated initial value when switching to `find-file`

### ISSUE THREAD

**Issue by egarrulo** [DarwinAwardWinner/ido-ubiquitous#87]
There is a problem with `read-directory-name` when there is an initial value: the value gets duplicated when dropping to `find-file`.  Maybe a test case will explain better.  Run `emacs -Q` and then evaluate the following code (the `load-path` will be different, of course, and if you are not on Linux, you will have to provide a different valid initial value):

    (ido-mode 1)
    (ido-everywhere 1)
    (add-to-list 'load-path "~/site-lisp/ido-ubiquitous/ido-ubiquitous-3.6")

    (require 'ido-ubiquitous)
    (ido-ubiquitous-mode 1)
    (read-directory-name "Directory: " nil nil t "/usr/local") ; existing path on Linux

IDO starts reading the directory name, but it will say "[No match]" (I don't know how this could be fixed, but this is a different problem). Anyway, press `C-f (ido-magic-forward-char)` when point is at the end of the input string (it should move there in a fraction of a second) and IDO switches to `find-file`.  However, now the initial value will be duplicated:

    Directory: ~//usr/local/usr/local

This does not happen when switching to `find-file` from IDO without IDO Ubiquituos, for instance `ido-find-file`.

Tested on GNU Emacs 24.5 and IDO Ubiquituos 3.6.

Thanks for your attention.

**Comment by DarwinAwardWinner** [comment]
This is a bug in ido and has nothing to do with ido-ubiquitous.

**Comment by egarrulo** [comment]
> This is a bug in ido and has nothing to do with ido-ubiquitous.

Indeed.  I don't know how I didn't realize that.  Sorry.

> Also, you are using the INITIAL argument to read-directory-name incorrectly

What do you mean, please?  That the INITIAL argument should end with a `/`?  Thanks.

**Comment by DarwinAwardWinner** [comment]
The INITIAL argument should not have any path separators in it at all. The starting path is specified in the DIR argument.
