### ISSUE TITLE
I can't use ido-ubiquitous in multi-term

### ISSUE THREAD

**Issue by yu-yuxuan** [DarwinAwardWinner/ido-ubiquitous#88]
I use multi-term for zsh. The problem is that there is no auto-complete in this mode. Is there any code I need to add ? Thank you very much.

**Comment by DarwinAwardWinner** [comment]
I'm not familiar with multi-term mode. Can you give me an example of a command or sequence of actions that you expect to trigger ido completion?

**Comment by yu-yuxuan** [comment]
@DarwinAwardWinner  One example is `cd .emacs.d` . When I use `M-x shell` and type `cd .e`. It will show `cd .emacs.d`. But when I use multi-term. it didn't appear. Thank you.

**Comment by DarwinAwardWinner** [comment]
As far as I know, ido-ubiquitous has nothing to do with shell mode, multi-term, or adding completion where there is none. It only deals with commands that read completions from the minibuffer. I don't think your problem is related to ido-ubiquitous
