### ISSUE TITLE
Add etags-select commands to ido-ubiquitous-default-function-overrides

### ISSUE THREAD

**Issue by Wilfred** [DarwinAwardWinner/ido-ubiquitous#89]
I added the following to my init.el:

```lisp
(add-to-list 'ido-ubiquitous-command-overrides
             '(enable prefix "etags-select"))

```

Without this, ido-ubiquitous does not give ido completion for `etags-select-find-tag`, which is part of https://github.com/emacsmirror/etags-select

**Comment by DarwinAwardWinner** [comment]
Thanks for the report! This will be included in the next release.
