### ISSUE TITLE
ido-ubiquitous should notify on update when new overrides are available.

### ISSUE THREAD

**Issue by DarwinAwardWinner** [DarwinAwardWinner/ido-ubiquitous#90]
Two new options should be added: `ido-ubiquitous-notify-on-new-overrides` (default t) and `ido-ubiquitous-auto-add-new-overrides` (default nil).

**Comment by DarwinAwardWinner** [comment]
Actually, these two options will be merged into a single variable with 3 possible values: nil, t, and ask. In addition, whenever the user adds a custom overrides, ido-ubiquitous should politely request that they report it on Github, or via email (with an option to disable the nagging).

**Comment by dgutov** [comment]
Why does it write to my `custom.el`? I never stored the value of `ido-ubiquitous-command-overrides` there.

**Comment by DarwinAwardWinner** [comment]
Hmm. that's a bug. Sorry about that. I'll investigate it when I get the chance.

**Comment by DarwinAwardWinner** [comment]
See https://github.com/DarwinAwardWinner/ido-ubiquitous/issues/104
