### ISSUE TITLE
*Compile-Log* buffer messages

### ISSUE THREAD

**Issue by ramblehead** [DarwinAwardWinner/ido-ubiquitous#91]
Getting the following bunch of warnings in ```*Compile-Log*``` buffer:

```
.emacs.d/lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
.emacs.d/lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
.emacs.d/lisp/ido-ubiquitous.el:Warning: reference to free variable
...
```
Running on Ubuntu 14.04 LTS, Emacs from native apt repository.

Dirty fix in init file:
```elisp
(defvar ido-ubiquitous-debug-mode nil)
(require 'ido-ubiquitous)
```

**Comment by DarwinAwardWinner** [comment]
I'm not sure why you would be getting those messages. The variable is declared here: https://github.com/DarwinAwardWinner/ido-ubiquitous/blob/master/ido-ubiquitous.el#L95

**Comment by ramblehead** [comment]
That is strange indeed.

Investigating it a bit further:

When running ido-ubiquitous manually with default e-macs settings (i.e. renaming my init dir), the messages do not occur.

Changing ```(defvar ido-ubiquitous-debug-mode)``` line in ```ido-ubiquitous.el``` to ```(defvar ido-ubiquitous-debug-mode nil)``` seems to resolve the issue as well.

Must be related to my other settings/packages loaded before/after ido-ubiquitous...

Moving the following initialisation lines:
```elisp
(require 'ido-ubiquitous)
(ido-ubiquitous-mode t)
```
to the top of my init.el makes subject messages disappear.

Moving ido-ubiquitous initialisation lines down of init.el step-by-step reveals the conflicting function: ```(ffap-bindings)```. When ```(ido-ubiquitous-mode t)``` is called before ```(ffap-bindings)```, the subject messages do not occur. When it is called after, messages do occur.

Could you replicate this issue with ```(ffap-bindings)```?

P. S. Is it ```(ido-ubiquitous-mode t)``` or ```(ido-ubiquitous-mode 1)```?

**Comment by DarwinAwardWinner** [comment]
By convention, Emacs modes are activated by passing a positive number, so it's `(ido-ubiquitous-mode 1)`.

**Comment by DarwinAwardWinner** [comment]
I don't see anything in the code of ffap that would interfere with ido-ubiquitous and trigger this warning.

**Comment by ramblehead** [comment]
Thank you for your reply! - changed to ```(ido-ubiquitous-mode 1)```

Further investigations:
Renaming my ```.emacs.d``` to ```x.emacs.d```. Copying ```ido-completing-read+.el``` and ```ido-ubiquitous.el``` to ```/usr/local/share/emacs/site-lisp```. Creating ```~/.emacs.el``` with the following content:

```elisp
(ffap-bindings)
(require 'ido-ubiquitous)
(ido-ubiquitous-mode 1)
```

Starting emacs. Observing subject messages in ```*Compile-Log*```. Moving ```(ffap-bindings)``` after ```(ido-ubiquitous-mode 1)```. Messages disappear.

Will try to investigate it further - do not have much experience debugging lisp...

**Comment by DarwinAwardWinner** [comment]
If you can give me directions to reproduce these warnings starting from `emacs -Q`, I can spend some time debugging them.

**Comment by ramblehead** [comment]
Pulled the latest ido-ubiquitous version from github - thank you!

Unfortunately, the warnings are still there. I am not sure how to use emacs with -Q. Do you mean using ```M-x ielm```? If yes, here is what I have (running emacs with -Q):
```elisp
*** Welcome to IELM ***  Type (describe-mode) for help.
ELISP> (add-to-list 'load-path "/home/rh/.emacs.d/lisp/")
("/home/rh/.emacs.d/lisp/" "/usr/share/emacs/24.3/lisp" "/usr/share/emacs/24.3/lisp/vc" "/usr/share/emacs/24.3/lisp/url" "/usr/share/emacs/24.3/lisp/textmodes" "/usr/share/emacs/24.3/lisp/progmodes" "/usr/share/emacs/24.3/lisp/play" "/usr/share/emacs/24.3/lisp/org" "/usr/share/emacs/24.3/lisp/nxml" "/usr/share/emacs/24.3/lisp/net" "/usr/share/emacs/24.3/lisp/mh-e" "/usr/share/emacs/24.3/lisp/mail" "/usr/share/emacs/24.3/lisp/language" "/usr/share/emacs/24.3/lisp/international" "/usr/share/emacs/24.3/lisp/gnus" "/usr/share/emacs/24.3/lisp/eshell" "/usr/share/emacs/24.3/lisp/erc" "/usr/share/emacs/24.3/lisp/emulation" "/usr/share/emacs/24.3/lisp/emacs-lisp" "/usr/share/emacs/24.3/lisp/cedet" "/usr/share/emacs/24.3/lisp/calendar" "/usr/share/emacs/24.3/lisp/calc" "/usr/share/emacs/24.3/lisp/obsolete" "/usr/share/emacs/24.3/leim")

ELISP> (ffap-bindings)
(ffap-ro-mode-hook)

ELISP> (require 'ido-ubiquitous)
ido-ubiquitous
ELISP> (ido-ubiquitous-mode 1)
t
ELISP> 
```
After the last command, emacs creates another buffer called ```*Compile-Log*``` with the following content (not cutting anything):
```
lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
lisp/ido-ubiquitous.el:Warning: reference to free variable
    `ido-ubiquitous-debug-mode'
```

Running emacs from Ubuntu 14.04 LTS native repo. ```M-x version``` produces the following:
```GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-07 on lamiak, modified by Debian```

Still using ```(defvar ido-ubiquitous-debug-mode nil)``` before ```(ido-ubiquitous-mode 1)``` which seems to cure the issue (at least visually).

**Comment by DarwinAwardWinner** [comment]
`emacs -Q` means starting up a terminal and running `emacs -Q`, which starts up emacs without loading any user or system init files, so you just get the completely default emacs configuration. Then, starting from there, figure out the steps to produce these warnings. This way I can rule out interactions with other aspects of your config, other packages, and a whole host of possible issues.

**Comment by ramblehead** [comment]
I think, my previous message describes those steps. Apologies if too many details. In short:
run ```emacs -Q``` from terminal, In emacs use the followin commands:
```elisp
(add-to-list 'load-path "/path/to/ido-ubiquitous/")
(ffap-bindings)
(require 'ido-ubiquitous)
(ido-ubiquitous-mode 1)
```
On my sistem, it creates ```*Compile-Log*``` buffer with warnings.

**Comment by DarwinAwardWinner** [comment]
Ok, I can indeed reproduce this. I'll look into it when I get the chance.

**Comment by DarwinAwardWinner** [comment]
Ok, I pushed a change to my bleeding edge branch. Can you please see if your problem is fixed when using this version? https://raw.githubusercontent.com/DarwinAwardWinner/ido-ubiquitous/bleeding-edge/ido-ubiquitous.el

**Comment by ramblehead** [comment]
The sequence is as before (running ```emacs -Q```):
```
(add-to-list 'load-path "/path/to/ido-ubiquitous/")
(ffap-bindings)
(require 'ido-ubiquitous)
```
The last command outputs ```*** Eval error ***  Cannot open load file: s```

**Comment by DarwinAwardWinner** [comment]
Oh yeah, I added a dependency on the s package for string manipulation. You can install it from MELPA using package.el. If you already use MELPA, it's probably installed already, and you can just run `package-initialize` inside your emacs session to make it available.

**Comment by ramblehead** [comment]
Installed ```s.el```. Output after ```(require 'ido-ubiquitous)```:
```*** Eval error ***  Symbol's function definition is void: set-default-toplevel-value```

**Comment by DarwinAwardWinner** [comment]
Hmm, looks like that function has only recently been added to Emacs. I wish there was a way to look up the Emacs version that added a given function or variable so I could avoid issues like this. I'll push a fix in a few minutes.

**Comment by DarwinAwardWinner** [comment]
Ok, give it another try with the latest version.

**Comment by ramblehead** [comment]
No more warnings - just works. Great job! Thank you.
