### ISSUE TITLE
The return of byte-compilation warnings

### ISSUE THREAD

**Issue by mrkkrp** [DarwinAwardWinner/ido-ubiquitous#98]
Possibly related to #91. After a recent upgrade, the following warnings have begun to appear on Emacs start up:

```
Warning (bytecomp): reference to free variable ‘ido-require-match’
Warning (bytecomp): reference to free variable ‘ido-cur-list’
Warning (bytecomp): reference to free variable ‘ido-cr+-debug-mode’
Warning (bytecomp): reference to free variable ‘ido-require-match’
Warning (bytecomp): reference to free variable ‘ido-cur-list’
Warning (bytecomp): reference to free variable ‘ido-require-match’
Warning (bytecomp): reference to free variable ‘ido-cur-list’
```

There was none of them till this day. This means that latest commits somehow turned it on.

**Comment by DarwinAwardWinner** [comment]
I have received so many reports of different variable-scope-related warnings produced by ido-ubiquitous, and I have yet to discover how to consistently reproduce any of them. So there's really nothing I can do to fix them that isn't equally likely to just create new and different warnings.

**Comment by mrkkrp** [comment]
I think the solution is very simple, look at commits on 22 November and find out which of them turns this on. Since you seem to be unable to reproduce this anyway, I could do it myself and send a PR.

**Comment by DarwinAwardWinner** [comment]
Ok, the only commit that touches lines involving those variables is this one: https://github.com/zahardzhan/ido-ubiquitous/commit/d4cb80a391b5da9843d09315278b37d03b9eca7b which comes from a pull request #96 whose purpose was to eliminate some *other* warnings, which I also cannot reproduce, of course. I have no idea what the correct solution is, especially in the case of `ido-cr+-debug-mode`, where switching from leaving the variable unbound to giving it a default value somehow causes a free variable warning.

**Comment by mrkkrp** [comment]
@DarwinAwardWinner, Strangely, reverting that commit doesn't solve the problem. Cause of the problem must be something else.

**Comment by mrkkrp** [comment]
This commit introduces the warnings: 4306d4ca.

**Comment by DarwinAwardWinner** [comment]
The two ido variables are declared, but not bound, by ido.el.

As for reproducing the warnings, it looks like maybe those warnings only happen during byte-compilation, so maybe they only happen the first time after ido-ubiquitous is updated, unless you delete the elc file.
